name: Go

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MONGOID_TEST_DB: "0"
      MONGOID_LOG_LEVEL: warn
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Get
        run: go get -t -v

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go run github.com/markbates/grift test

      - name: Bench
        run: go run github.com/markbates/grift test:bench

      - name: Vet
        run: go vet
